### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by garyo** [xiaoxiangmoe/vite-plugin-commonjs-externals#5]
I just added this plugin to my vite config, and now I get this error when running `yarn dev`:
```
$ vite
failed to load config from /home/garyo/dss/product/horizon/horizon/packages/camera-move-designer/vite.config.ts
error when starting dev server:
/home/garyo/dss/product/horizon/horizon/node_modules/vite-plugin-commonjs-externals/dist/index.js:31
        if (node?.type !== 'ImportDeclaration') {
                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/garyo/dss/product/horizon/horizon/packages/camera-move-designer/vite.config.ts:35:56)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (/home/garyo/dss/product/horizon/horizon/node_modules/vite/dist/node/chunks/dep-9f74b403.js:77249:20)
```

My vite.config.js:
```
import * as path from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import commonjsExternals from 'vite-plugin-commonjs-externals'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(),
            commonjsExternals({externals: ['make-error-cause']})],
  resolve: {
    alias: [{find: '@', replacement: path.resolve(__dirname, '../front-end/src')}]
  },
  server: {
    fs: {
      allow: ['..']
    }
  }
})
```

which looks like my typescript is too old, but I have tsc --version = 'Version 4.4.3' so I don't know. I see that `dist/index.js` is a Javascript file, so perhaps it should not have Typescript syntax?

**Comment by beorn** [comment]
Perhaps @xiaoxiangmoe can set `target: "ES6"` in `tsconfig.json` to have tsc transpile to a version of JS that doesn't support the optional chaining syntax.

**Comment by xiaoxiangmoe** [comment]
See [0.1.3](https://www.npmjs.com/package/vite-plugin-commonjs-externals/v/0.1.3)
