### ISSUE TITLE
TypeError: commonjsExternals is not a function

### ISSUE THREAD

**Issue by KonradHoeffner** [xiaoxiangmoe/vite-plugin-commonjs-externals#6]
With vite-plugin-commonjs-externals version ^0.1.1 and vite version ^2.6.5 I get the following error with `npm run dev`:
```
failed to load config from /home/konrad/projekte/snik/cytoscape/vite.config.js
error when starting dev server:
TypeError: commonjsExternals is not a function
    at file:///home/konrad/projekte/snik/cytoscape/vite.config.js?t=1633965357544:6:11
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/home/konrad/projekte/snik/cytoscape/node_modules/vite/dist/node/chunks/dep-55830a1a.js:68524:31)
    at async resolveConfig (/home/konrad/projekte/snik/cytoscape/node_modules/vite/dist/node/chunks/dep-55830a1a.js:68105:28)
    at async createServer (/home/konrad/projekte/snik/cytoscape/node_modules/vite/dist/node/chunks/dep-55830a1a.js:66619:20)
    at async CAC.<anonymous> (/home/konrad/projekte/snik/cytoscape/node_modules/vite/dist/node/cli.js:687:24)
```

## vite.config.js

Following <https://www.npmjs.com/package/vite-plugin-commonjs-externals>, my `vite.config.js` is:

```
import commonjsExternals from 'vite-plugin-commonjs-externals';

export default {
	sourcemap: true,
	plugins: commonjsExternals({
		externals: ['path', /^level-js(\/.+)?$/],
	  }),
	build: {
		target: "es2020",
		rollupOptions: {
			output: {
				assetFileNames: "assets/[name][extname]",
			},
		},
	},
};
```

**Comment by KonradHoeffner** [comment]
`plugins: [commonjsExternals.default({externals: ['path', /^level-js(\/.+)?$/],})],` does not throw that error, however now it does not seem to have any effect.

**Comment by dbrgn** [comment]
@KonradHoeffner did you find a solution?

**Comment by beorn** [comment]
I got this error too. 

Not sure if it helps, but when I do:

```ts
import * as commonjsExternals from 'vite-plugin-commonjs-externals';
console.log(commonExternals);
```

it actually yields `{ default: { default: [Function: commonjsExternalsPlugin] }`

**Comment by MaxSpiro** [comment]
you have to import it as default and still call .default
import commonJsExternals from ...
plugins: [commonJsExternals.default()]

even though typescript yells, it works

**Comment by liuyike98** [comment]
> even though typescript yells, it works

it works
